//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserRegistration
    {
        public int AdvertiserId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CNIC { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserCode { get; set; }
        public Nullable<bool> IsAdvertiserActive { get; set; }
        public Nullable<bool> IsNewRequest { get; set; }
        public Nullable<bool> IsPaidAdvertiser { get; set; }
        public Nullable<int> AdvertiserPackage { get; set; }
        public byte[] DocumentImage { get; set; }
        public byte[] NICFrontImage { get; set; }
        public byte[] NICBackImage { get; set; }
        public byte[] ProfileImage { get; set; }
        public string AccountTitle { get; set; }
    }
}
