//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCommissionBalance
    {
        public int UserCommBalanceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> UserCommBalance { get; set; }
        public string UserCommPosition { get; set; }
        public Nullable<bool> UserCommIsLeft { get; set; }
        public Nullable<bool> UserCommIsRight { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
