//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoPackTbl
    {
        public int VideoPackId { get; set; }
        public int VideoPackPkgId { get; set; }
        public int VideoPackCatId { get; set; }
        public string VideoPackName { get; set; }
        public string VideoPackDesc { get; set; }
        public string VideoPackVideos { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte[] VideoPackImage { get; set; }
        public Nullable<int> AdvertiserId { get; set; }
        public string AdvertiserName { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<int> NumberOfViews { get; set; }
        public Nullable<bool> IsYoutubeURL { get; set; }
    }
}
