//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSleepingPatener
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTreeUserDetailData
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Country { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CNIC { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<bool> IsThisFirstUser { get; set; }
        public int SponsorId { get; set; }
        public int DownlineMemberId { get; set; }
        public Nullable<int> UpperId { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserCode { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public Nullable<bool> IsNewRequest { get; set; }
        public string UserPosition { get; set; }
        public Nullable<bool> IsPaidMember { get; set; }
        public Nullable<int> UserPackage { get; set; }
        public byte[] DocumentImage { get; set; }
        public Nullable<bool> IsSleepingPartner { get; set; }
        public Nullable<bool> IsSalesExecutive { get; set; }
        public string UserDesignation { get; set; }
        public Nullable<bool> IsWithdrawalOpen { get; set; }
        public byte[] NICImage { get; set; }
        public byte[] ProfileImage { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<bool> IsVerify { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public byte[] NICImage1 { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public string fcm { get; set; }
        public int Tree_ID { get; set; }
        public string Tree_Name { get; set; }
        public Nullable<int> TreeUserId { get; set; }
        public Nullable<int> TreeDownlineMemberId { get; set; }
        public int Parent_ID { get; set; }
        public string Seq_index { get; set; }
        public string Full_index { get; set; }
        public string TreeUserPosition { get; set; }
    }
}
