//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoPackCatTbl
    {
        public int Id { get; set; }
        public string Category_Name { get; set; }
        public string Category_Desc { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
